context:
  name: font-ttf-adwaita
  version: "51.0"
  version_maj: ${{ (version | split('.'))[:1] | join('.') }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://download.gnome.org/sources/adwaita-fonts/${{ version_maj }}/adwaita-fonts-${{ version }}.tar.xz
  sha256: fa104ae2c1b96580d322f563ffe8b2dfca5296b0eca4971efd2d8011405123d2

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p $PREFIX/fonts
    - cp mono/*.ttf $PREFIX/fonts/
    - cp sans/*.ttf $PREFIX/fonts

tests:
  - package_contents:
      strict: true
      files:
        - fonts/AdwaitaSans-Italic.ttf
        - fonts/AdwaitaSans-Regular.ttf
        - fonts/AdwaitaMono-Bold.ttf
        - fonts/AdwaitaMono-BoldItalic.ttf
        - fonts/AdwaitaMono-Italic.ttf
        - fonts/AdwaitaMono-Regular.ttf

about:
  homepage: https://gitlab.gnome.org/GNOME/adwaita-fonts
  summary: "The typefaces for GNOME"
  description: |
    Adwaita Sans, a variation of Inter, and Adwaita Mono, Iosevka customized to match Inter.
  license: OFL-1.1
  license_file: LICENSE
  repository: https://gitlab.gnome.org/GNOME/adwaita-fonts

extra:
  recipe-maintainers:
    - haecker-felix
    - danyeaw
